name: buildx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true
          
      - name: Setup Java 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
        
      - name: Maven Package
        run: mvn -B clean package --file pom.xml

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker Buildx (build)
        uses: docker/build-push-action@v2.7.0
        if: success() && !contains(github.ref, 'main')
        with:
          push: false
          build-args: ARCH=amd64
          platforms: linux/amd64
          tags: vprokopiv/ytbot:latest

      - name: Docker Login
        if: success() && contains(github.ref, 'main')
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (push)
        uses: docker/build-push-action@v2.7.0
        if: success() && contains(github.ref, 'main')
        with:
          push: true
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          platforms: linux/amd64
          tags: vprokopiv/ytbot:latest

      - name: Inspect Image
        if: always() && github.event_name != 'pull_request' && contains(github.ref, 'main')
        run: |
          docker buildx imagetools inspect vprokopiv/ytbot:latest
      - name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json
    
