name: buildx

on:
  push:
    branches: [ main ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
    
      - name: Setup Java 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: maven
        
      - name: Maven Package
        run: mvn -B clean package --file pom.xml

      - name: Docker Login
        if: success() && contains(github.ref, 'main')
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Buildx Update
        run: sh update-images.sh
